FROM maven:3 as building-app
WORKDIR app

ADD src src
add pom.xml pom.xml
RUN mvn package

FROM eclipse-temurin:17-jre
WORKDIR app
COPY --from=building-app  /app/target/curs10.jar application.jar
CMD java -jar application.jar